In [1]:
"""
    itchat: A complete and graceful API for Wechat
    developed by LitterCoder
        http://itchat.readthedocs.io/zh/latest/
        https://github.com/littlecodersh/ItChat
    
    Overview of my wechat friends
"""
import itchat as ic
ic.login()

Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as 干脆面、

In [2]:
friends = ic.get_friends(update = True)[0:]
print(friends[0])

{'UserName': u'@fadbbf4c99e7fdf8d28eca61e3f42508ee0e24dd23a57d33fc187d865424ee12', 'City': '', 'DisplayName': '', 'UniFriend': 0, 'OwnerUin': 0, 'MemberList': <ContactList: []>, 'PYQuanPin': u'', 'RemarkPYInitial': u'', 'Uin': 1620773101, 'AppAccountFlag': 0, 'VerifyFlag': 0, 'Province': '', 'KeyWord': '', 'RemarkName': u'', 'PYInitial': u'', 'ChatRoomId': 0, 'HideInputBarFlag': 0, u'HeadImgFlag': 1, 'EncryChatRoomId': '', 'AttrStatus': 0, 'SnsFlag': 17, 'MemberCount': 0, u'WebWxPluginSwitch': 0, 'Alias': '', 'Signature': u'', 'ContactFlag': 0, 'NickName': u'\u5e72\u8106\u9762\u3001', 'RemarkPYQuanPin': u'', 'HeadImgUrl': u'/cgi-bin/mmwebwx-bin/webwxgeticon?seq=4834868&username=@fadbbf4c99e7fdf8d28eca61e3f42508ee0e24dd23a57d33fc187d865424ee12&skey=@crypt_15ca74d8_47792e9df07d69650c643c3c10c89fc3', 'Sex': 1, 'StarFriend': 0, 'Statues': 0}

In [3]:
# Sex distribution of my friends
male, female, unknown = 0, 0, 0
for i in friends[1:]:
    sex = i['Sex']
    if sex == 1:
        male += 1
    elif sex == 2:
        female += 1
    else:
        unknown += 1

total = float(male + female + unknown)
sex_info = (male, float(male)*100 / total, female, float(female)*100 / total, unknown, float(unknown)*100 / total)
print('male: %d -> %f %%\nfemale: %d -> %f %%\nunknown: %d -> %f %%' % sex_info)

male: 181 -> 48.918919 %
female: 169 -> 45.675676 %
unknown: 20 -> 5.405405 %

In [4]:
# Create a DataFrame to store all friends information
import pandas as pd
# Some informations like NickName, RemarkName are personal privacy, I will not display them here
friends_private_df = pd.DataFrame(friends[1:])

In [5]:
friends_public_df = friends_private_df.loc[:, ['City', 'Province']]
friends_public_df.iloc[:20]

             City    Province
0              杭州          浙江
1   New York City    New York
2              昆明          云南
3              杭州          浙江
4
5              安庆          安徽
6              杭州          浙江
7
8              杭州          浙江
9
10       New York    New York
11    Los Angeles  California
12  New York City    New York
13             南京          江苏
14             杭州          浙江
15                         上海
16             杭州          浙江
17             杭州          浙江
18             杭州          浙江
19             台州          浙江

In [6]:
friends_public_df.groupby('Province').count()

                    City
Province
                      38
Addu Atoll             1
British Columbia       1
California             4
Cuando Cubango         1
Delaware               1
DistrictofColumbia     1
Dublin                 1
England                2
Illinois               3
Istanbul               1
Massachusetts          2
Michigan               1
Montreal               1
New York              31
NewYork               12
Northern Territory     1
Osaka                  1
Potsdam                1
Seoul                  1
Texas                  1
Tokyo                  1
Toronto                1
Venice                 1
Washington             1
Western Australia      1
Zurich                 1
上海                    13
云南                     1
北京                    10
四川                     4
安徽                     6
山东                     3
山西                     1
广东                     7
广西                     1
江苏                     7
江西                     1
河南                     1
浙江                   194
湖南                     1
甘肃                     2
福建                     3
辽宁                     2
陕西                     1

In [7]:
# Convert 'NewYork' to 'New York'
idx_ny = friends_public_df['Province'] == 'NewYork'
friends_public_df.loc[idx_ny, ['Province']] = 'New York'

In [8]:
# Top 10 locations my friends come from
friends_public_df.groupby('Province').count().sort(['City'], ascending = False).head(10)

C:\Users\Bangda\Anaconda2\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app

            City
Province
浙江           194
New York      43
              38
上海            13
北京            10
广东             7
江苏             7
安徽             6
California     4
四川             4

In [9]:
# Friends in Zhejiang
friends_zj = friends_public_df.loc[friends_public_df['Province'] == friends_public_df.iloc[0, 1]]
friends_zj.head()

   City Province
0    杭州       浙江
3    杭州       浙江
6    杭州       浙江
8    杭州       浙江
14   杭州       浙江

In [10]:
# Friends in cities of Zhejiang
friends_zj['City'].value_counts()

杭州    135
温州     15
宁波     15
台州      7
嘉兴      6
绍兴      5
金华      4
湖州      4
衢州      1
舟山      1
丽水      1
Name: City, dtype: int64